.gitignore
cloudformation/cloudformation.yml
cloudformation/dynamodb.yml
index.js
lib/capi.js
lib/facebook.js
lib/user-store.js
package.json

(and various improvements)
- The bot will push a morning briefing (a set of 5 links) to a user at a time specified by them (restricted to 6, 7 or 8am).
- The user's ID and preferences are stored in a dynamodb table.
- It takes the user's current timezone offset from facebook to calculate the correct time to push.
- At intervals of 15 mins, it checks for users in the dynamo table with the current time (all done in UTC). It checks at this point to see if the user's timezone has changed.
The user can request headlines (editors-picks) or trending (most-viewed) at any time. The front (uk/us/au/international) is determined using the facebook user's locale.

Add scheduling of morning briefings

---

index.js
lib/user-store.js

We decide which front to use by checking the user's facebook locale string (e.g. "en_GB" => "uk")
It appears this never changes, so e.g. a British person who moved to the US still has "en_GB" (which makes sense).
We'll still use this as a default for now, but the user can now change it by clicking "Change edition". The options are presented as a carousel (like with the headlines), because you're only allowed a max of 3 buttons. In future we could add images for each tile in the carousel.
Note - we have plans to add bots to the US and AU facebook pages as well. The default edition can then be specific to the facebook page.

Make edition configurable

---

index.js
lib/capi.js
lib/messages.js

New users should first be presented with a 'Get started' button (this is a standard facebook messenger thing - https://developers.facebook.com/docs/messenger-platform/thread-settings/get-started-button).
This triggers the `start` event, which adds the user to dynamodb and greets them.
However, the Get started button keeps disappearing from facebook messenger (@chriswilk has asked facebook to sort this out). We should defend against this by always looking up the user in dynamo whenever a message is received from facebook. So even if they haven't arrived via the Get started button, we'll add them to dynamo and send the initial greeting.

Always lookup user in dynamo

---

index.js

Immediately after a new user subscribes for the first time, a menu button incorrectly says "Subscribe" rather than "Manage subscription". This fixes that.
(also added logging for the `start` event)

Fix initial menu for new users

---

index.js

Setting this turns each tile on the carousel into a link, which will open in Instant Articles if available there. This means we can remove the "Read story" button.
This is a bit of a hack, since FB doesn't provide a way of sharing links from the carousel. A "Share" button appears below each tile, and when clicked we send a link to the article as a text message. Messenger automatically accompanies that link with a share button, allowing the user to share on Messenger only.
The URL has the campaign code `fb_newsbot_share`.

Use item_url on elements and add 'share' button

---

index.js
lib/capi.js
package.json

Currently the app sends a CAPI request every time it needs the editors-picks or most-viewed. This is not at all scalable, especially in the case of the morning briefing.
Cached results are considered fresh for 30 seconds.

Cache capi results

---

index.js

This caused people to miss their morning briefings this morning :(
Before sending a morning briefing, it checks if the user's timezone has changed (according to facebook). It turns out sometimes this field is missing in the facebook response - if this happens it now just pushes the morning briefing anyway.
This is a good reason for switching to scalajs - the bug is the result of an incorrect variable name in an error-handling branch after refactoring!

Fix handling of missing timezone in facebook response

---

build.sbt
cloudformation/cloudformation.yml
src/main/scala/com/gu/facebook_news_bot/BotConfig.scala
src/main/scala/com/gu/facebook_news_bot/BotService.scala
src/main/scala/com/gu/facebook_news_bot/briefing/MorningBriefingPoller.scala
src/main/scala/com/gu/facebook_news_bot/models/User.scala
src/main/scala/com/gu/facebook_news_bot/services/SQS.scala
src/main/scala/com/gu/facebook_news_bot/state/MainState.scala
src/main/scala/com/gu/facebook_news_bot/utils/FacebookMessageBuilder.scala
src/main/scala/com/gu/facebook_news_bot/utils/ResponseText.scala

This matches the morning briefing currently sent by the old node app.
A new actor object polls an SQS queue for users who should receive their morning briefings now, which is populated by the [lambda](https://github.com/guardian/facebook-news-bot-scheduler).
A carousel of editors-picks is sent. It also checks if the user's timezone has changed.
I've added the `variant` field to the User model (which is stored in dynamodb). This will be used for A/B testing later.

Morning briefing

---

src/main/scala/com/gu/facebook_news_bot/services/Facebook.scala

Before:
`message --> facebookActor`
After:
`message --> throttler --> facebookActor`
Oops.

Fix throttling of facebook messages

---

src/main/scala/com/gu/facebook_news_bot/BotConfig.scala
src/main/scala/com/gu/facebook_news_bot/BotService.scala
src/main/scala/com/gu/facebook_news_bot/utils/Verification.scala

See https://developers.facebook.com/docs/messenger-platform/webhook-reference#security for details.
FB includes an X-Hub-Signature header in its requests, which we can check against the hash of the body using the secret for the FB app.

Verify signature in header

---

src/main/scala/com/gu/facebook_news_bot/models/FacebookModels.scala
src/main/scala/com/gu/facebook_news_bot/state/MainState.scala
src/main/scala/com/gu/facebook_news_bot/utils/FacebookMessageBuilder.scala
src/main/scala/com/gu/facebook_news_bot/utils/ResponseText.scala
src/test/resources/facebookResponses/headlines.json
src/test/resources/facebookResponses/moreHeadlines.json
src/test/resources/facebookResponses/morePoliticsHeadlines.json
src/test/resources/facebookResponses/newUser.json
src/test/resources/facebookResponses/politicsHeadlines.json
src/test/resources/facebookResponses/yesSubscribe.json

Quick replies are better than buttons because:
1. We can have more than 3
2. They vanish after the next message. Buttons persist, which means they can be clicked out of context later on
This change replaces the menu buttons with quick replies, and adds a new quick reply, "Suggest something". This is for telling the user that they can ask for topics. When we add more features in the future we can use this menu to tell users about them.

Menu quick replies, changes to the copy

---

src/main/scala/com/gu/facebook_news_bot/services/Capi.scala
src/main/scala/com/gu/facebook_news_bot/state/MainState.scala
src/main/scala/com/gu/facebook_news_bot/utils/FacebookMessageBuilder.scala
src/test/resources/facebookResponses/morePoliticsHeadlines.json
src/test/resources/facebookResponses/politicsHeadlines.json

Two improvements to the set of quick replies after the carousel:
1. If user is currently viewing stories for a topic, the `more` quick reply should specify the topic, e.g. "More politics stories" instead of just "More stories"
2. Filter out the quick reply for the topic that is currently being viewed.

Improve quick replies after carousel

---

src/main/scala/com/gu/facebook_news_bot/BotService.scala
src/main/scala/com/gu/facebook_news_bot/models/FacebookModels.scala
src/main/scala/com/gu/facebook_news_bot/state/MainState.scala
src/main/scala/com/gu/facebook_news_bot/state/State.scala

The text field on the message from facebook should actually be optional. I discovered this when a user sent a message with a gif and no text, and the app didn't reject it properly. FB then refused to send any more messages until our app had handled it, so it basically stopped working in production.
Proof that it now rejects the gif properly:

Make text field optional. Handle and log rejections.

---

src/main/resources/application.conf
src/main/resources/logback.xml
src/main/scala/com/gu/facebook_news_bot/BotConfig.scala
src/main/scala/com/gu/facebook_news_bot/BotService.scala
src/main/scala/com/gu/facebook_news_bot/models/FacebookModels.scala
src/main/scala/com/gu/facebook_news_bot/services/Facebook.scala

Over the weekend the bot failed to send/receive requests frequently, for various reasons. This branch fixes it.
1. It hit akka-http's limit on maximum number of open requests. I've raised the limit a bit in the config file, but I've also changed the code to use a connection pool and a request queue, to ensure we stay within the limit.
2. Some requests arrive as streams. Normally they don't (in akka terms, they arrive with type `HttpEntity.Strict`), which is why I never saw this problem in CODE. But sometimes in PROD the requests arrive as streams and so need to be handled correctly. It's important to consume the entire entity, even if we're not interested in the body of a particular message - [docs](http://doc.akka.io/docs/akka/2.4/scala/http/common/http-model.html#HttpEntity).
3. Handle …

Http fixes

---

src/main/scala/com/gu/facebook_news_bot/state/MainState.scala

This fixes the case where an existing user deletes the messenger conversation, then opens a new one. When the `start` event is received for an existing user, the standard greeting + menu should be sent. This is different to the greeting for a new user.
Also made the greetings regex more flexible.

Handle 'start' event with existing user

---

src/main/scala/com/gu/facebook_news_bot/models/FacebookModels.scala
src/test/scala/com/gu/facebook_news_bot/TestService.scala

These fields come from the facebook graph api, but we only use the locale and timezone.

Remove unused facebook user fields

---

src/main/scala/com/gu/facebook_news_bot/BotConfig.scala
src/main/scala/com/gu/facebook_news_bot/briefing/CollectionsBriefing.scala
src/main/scala/com/gu/facebook_news_bot/briefing/MorningBriefingPoller.scala
src/main/scala/com/gu/facebook_news_bot/models/User.scala
src/main/scala/com/gu/facebook_news_bot/utils/FacebookMessageBuilder.scala

Currently we only have one kind of morning briefing, which is a carousel built from the editors-picks for the user's edition. This is followed by some quick_replies suggesting topics, plus a "More stories" quick_reply.
This change introduces an alternative morning briefing. This is also a carousel, but the greeting message and the content in the carousel are defined by Editorial, using the Collections tool. This will be followed by the same quick_replies as the old briefing, except the "More stories" quick_reply will be replaced with "Popular stories".
We use the front called `morning-briefing`. In here are two collections:
1. `morning-briefing` - the set of stories to be used.
2. `greeting-message` - has a single article whose headline is the greeting message to be used. This is a bit of …

Collections briefing

---

src/main/scala/com/gu/facebook_news_bot/briefing/CollectionsBriefing.scala

This bug became apparent with this morning's briefings because Editorial curated their first one.
It was incorrectly caching messages with user IDs, so some users were receiving it more than once and some users got nothing at all. It could have been worse, as I had scaled up the number of instances and only a proportion of UK users were getting curated briefings. But still, OOPS.

Fix curated briefing caching

---

src/main/scala/com/gu/facebook_news_bot/BotConfig.scala
src/main/scala/com/gu/facebook_news_bot/BotService.scala
src/main/scala/com/gu/facebook_news_bot/services/Facebook.scala
src/main/scala/com/gu/facebook_news_bot/state/MainState.scala
src/main/scala/com/gu/facebook_news_bot/utils/FacebookMessageBuilder.scala
src/main/scala/com/gu/facebook_news_bot/utils/ResponseText.scala
src/test/resources/facebookResponses/briefingTime.json
src/test/resources/facebookResponses/headlines.json
src/test/resources/facebookResponses/moreHeadlines.json
src/test/resources/facebookResponses/morePoliticsHeadlines.json
src/test/resources/facebookResponses/politicsHeadlines.json

The final quick reply after the carousel and in the menu now says "Support the Guardian":
Clicking this brings up a carousel with 3 links: membership, contributions, and Kath's long read:
I also made some small changes to help with running it locally.

"Support the Guardian" quick reply

---

src/main/scala/com/gu/facebook_news_bot/models/FacebookModels.scala
src/main/scala/com/gu/facebook_news_bot/state/SubscribeQuestionState.scala

Facebook have [*just*](https://developers.facebook.com/docs/messenger-platform/referral-params) added support for a `ref` parameter in m.me links to messenger. This means we can log referrals from e.g. Instant Articles.
When a new user arrives, the app now checks the `postback` object for a `referral` object.

Log referrals

---

src/main/scala/com/gu/facebook_news_bot/briefing/CollectionsBriefing.scala
src/main/scala/com/gu/facebook_news_bot/briefing/MorningBriefingPoller.scala

Only UK users get the `collections` briefing, so in order to compare click-through with the `editors-picks` briefing we need to filter out non-UK click-throughs.
We track which briefing they came from using the `variant` url param. This should not be included for non-uk users.

Append edition to variant name

---

src/main/scala/com/gu/facebook_news_bot/briefing/CollectionsBriefing.scala
src/main/scala/com/gu/facebook_news_bot/briefing/MorningBriefingPoller.scala

We need a precise count of how many of each morning briefing is sent out. This makes it easier to compare click-through from different morning briefings.

Log morning briefing variants

---

src/main/scala/com/gu/facebook_news_bot/utils/Loggers.scala

This causes a type conflict with the default timestamp field in kibana. It is useful to have the timestamp here though.

Change name of timestamp field in logging

---

src/main/scala/com/gu/facebook_news_bot/briefing/MorningBriefingPoller.scala
src/main/scala/com/gu/facebook_news_bot/models/User.scala
src/main/scala/com/gu/facebook_news_bot/services/Facebook.scala
src/main/scala/com/gu/facebook_news_bot/state/BriefingTimeQuestionState.scala
src/main/scala/com/gu/facebook_news_bot/state/StateHandler.scala
src/test/scala/com/gu/facebook_news_bot/TestService.scala

In general this change models facebook responses and handles errors better.
Errors can occur for a variety of reasons, but ordinarily should only happen when a user has deleted the conversation. Currently the app quietly fails to send morning briefings to any users who have done this, day after day. Really we'd like to track these users, to get a better idea of how many subscribers we really have.
Before sending a morning briefing, the app gets the user's data from FB, to check their timezone hasn't changed. If the user is not contactable, FB returns a 200 with an empty body. When this occurs, increment the `daysUncontactable` field in dynamodb.

Record uncontactable users

---

riff-raff.yaml

Riff-raff is about to support finding cloudformation stacks by tags.  The default behaviour for yaml configs will now be `cloudFormationStackByTags: true`.  Changing here to keep existing behaviour.

Find cloudformation by name rather than tags

---

src/main/scala/com/gu/facebook_news_bot/briefing/MorningBriefingPoller.scala
src/main/scala/com/gu/facebook_news_bot/services/Facebook.scala

I noticed some pending morning briefing messages being dropped at the weekend. This is because it uses an in-memory queue with a limit of 1000 messages. Scaling up to two instances solved the problem, but really we should be able to run a single instance and process the SQS queue more sensibly.
This branch changes how we poll the SQS queue of users who are due to receive their briefing. Now, it only resumes polling when the current batch of 10 briefings has been sent, meaning the message queue should always be small.
I was going to add a second queue, so that we have one queue for morning briefing requests and one for higher priority requests. But since SQS only allows us to read 10 items at a time, it's not really worth it anymore.

Change sqs polling

---

src/main/scala/com/gu/facebook_news_bot/BotConfig.scala
src/main/scala/com/gu/facebook_news_bot/briefing/MorningBriefingPoller.scala
src/main/scala/com/gu/facebook_news_bot/services/Facebook.scala
src/main/scala/com/gu/facebook_news_bot/state/BriefingTimeQuestionState.scala
src/main/scala/com/gu/facebook_news_bot/state/EditionQuestionState.scala
src/main/scala/com/gu/facebook_news_bot/state/FeedbackState.scala
src/main/scala/com/gu/facebook_news_bot/state/MainState.scala
src/main/scala/com/gu/facebook_news_bot/state/State.scala
src/main/scala/com/gu/facebook_news_bot/state/SubscribeQuestionState.scala
src/main/scala/com/gu/facebook_news_bot/utils/Loggers.scala

Currently the app sends event logs to kibana. Nobody likes Kibana.
FB now support custom event logging in their analytics tools. With this change, the app will send the same event logs to FB.
In the following image, I filtered the 'headlines' event by topic 'football'.
This isn't as useful as I'd hoped, as there doesn't seem to be a way of comparing datasets, e.g. comparing the number of requests for each topic. Also, the smallest time interval is one day.
Note - the event name field for facebook analytics needs to be `_eventName`, whereas the field it's been using in kibana is `event`. The solution for now is just to include both fields in the logs, each with the same value.

Send events to fb

---

cloudformation/dynamodb-users.yml
src/main/scala/com/gu/facebook_news_bot/models/User.scala
src/main/scala/com/gu/facebook_news_bot/state/FootballTransferStates.scala

As well as transfer notifications by team, users will get a daily link to the "Rumour Mill" series. This will go out at midday in the user's timezone. This time will be stored in a new field in the dynamodb users table - `footballRumoursTimeUTC`.
A lambda will check for users who are due to receive their notification using this field.

Store transfer rumour notification times

---

cloudformation/cloudformation.yml
src/main/scala/com/gu/facebook_news_bot/BotConfig.scala
src/main/scala/com/gu/facebook_news_bot/BotService.scala
src/main/scala/com/gu/facebook_news_bot/briefing/MorningBriefingPoller.scala
src/main/scala/com/gu/facebook_news_bot/football_transfers/FootballTransfer.scala
src/main/scala/com/gu/facebook_news_bot/football_transfers/FootballTransfersPoller.scala
src/main/scala/com/gu/facebook_news_bot/state/FootballTransferStates.scala
src/main/scala/com/gu/facebook_news_bot/utils/SQSPoller.scala
src/test/scala/com/gu/facebook_news_bot/FootballTransferTest.scala

The first commit refactors the `MorningBriefingPoller` to create a general `SQSPoller` trait. This will be used for more things in the future.
The `FootballTransfersPoller` polls a new SQS queue. This queue subscribes to the SNS topic of https://github.com/guardian/facebook-news-bot-football-transfers
The team crest image URLs are taken from the same api as the team aliases.

Transfer notifications

---

cloudformation/cloudformation.yml
src/main/scala/com/gu/facebook_news_bot/BotConfig.scala
src/main/scala/com/gu/facebook_news_bot/BotService.scala
src/main/scala/com/gu/facebook_news_bot/football_transfers/FootballTransfer.scala
src/main/scala/com/gu/facebook_news_bot/football_transfers/FootballTransferRumoursPoller.scala
src/main/scala/com/gu/facebook_news_bot/services/Capi.scala
src/main/scala/com/gu/facebook_news_bot/utils/FacebookMessageBuilder.scala
src/test/scala/com/gu/facebook_news_bot/DummyCapi.scala

Subscribers will get the latest edition of 'Rumour Mill' each day. 
The lambda (facebook-news-bot-football-rumours) decides who to send to and when, and also whether an article is fresh (newer than 24 hours old).
The 'Latest transfers' link goes to the interactive article.

Transfer rumour notifications

---

src/main/scala/com/gu/facebook_news_bot/briefing/MorningBriefingPoller.scala
src/main/scala/com/gu/facebook_news_bot/services/Facebook.scala
src/main/scala/com/gu/facebook_news_bot/state/FootballTransferStates.scala
src/test/scala/com/gu/facebook_news_bot/FootballTransfersSubscriptionTest.scala

On the 1st January ask all users if they'd like to subscribe to football transfers notifications immediately after their morning briefing (if they're not already subscribed).
Also in this PR:
- make `Facebook.send(messages)` send the next message only after receiving a response from FB. This doesn't necessarily guarantee delivery order, but it seems reliable so far.
- log when people say "no" to the subscription question.

Advertise football transfers notifications

---

src/main/scala/com/gu/facebook_news_bot/state/FootballTransferStates.scala

We'll hoping to refer lots of new users from football-related content on-platform, but it will be useful to know how many existing subscribers are interested in football transfers.
`notificationTimeUTC == "-"` means a user is not subscribed to the morning briefing.

Log whether a user is subscribed to morning briefing when they respond to the football transfers question

---

src/main/scala/com/gu/facebook_news_bot/football_transfers/FootballTransfersPoller.scala

Currently the app uses the crest of the club the player is going to, but if we don't have a crest for that club then it falls back on a default image.
This happens a lot, e.g. a player going out on loan to a smaller club. I think it's better to fall back on the crest of the club they're coming from.
E.g.

Use fromClub crest if no toClub crest available

---

src/main/scala/com/gu/facebook_news_bot/state/MainState.scala

E.g. when an existing user clicks the Messenger link in an Instant Article.
Currently it says "Sorry, I didn't understand that" etc.
It should just greet them.

Greet existing user on referral

---

src/main/scala/com/gu/facebook_news_bot/state/BriefingTimeQuestionState.scala
src/main/scala/com/gu/facebook_news_bot/state/EditionQuestionState.scala
src/main/scala/com/gu/facebook_news_bot/state/FootballTransferStates.scala
src/main/scala/com/gu/facebook_news_bot/state/MainState.scala
src/main/scala/com/gu/facebook_news_bot/state/ManageMorningBriefingState.scala
src/main/scala/com/gu/facebook_news_bot/state/StateHandler.scala
src/main/scala/com/gu/facebook_news_bot/state/SubscribeQuestionState.scala
src/main/scala/com/gu/facebook_news_bot/state/UnsubscribeState.scala
src/main/scala/com/gu/facebook_news_bot/utils/ResponseText.scala
src/test/resources/facebookRequests/unsubscribeMenu.json
src/test/resources/facebookResponses/changeFront.json
src/test/resources/facebookResponses/unsubscribeMenu.json
src/test/resources/facebookResponses/yesSubscribe.json
src/test/scala/com/gu/facebook_news_bot/SubscriptionTest.scala

1. Ask which edition a user wants while subscribing to the morning briefing. Previously the edition could only be set from the subscriptions menu, which isn't obvious.
2. Handle unsubscribe requests better. Previously saying "unsubscribe" out of context would unsubscribe from the morning briefing. Now it asks the user which service to unsubscribe from, based on their current subscriptions.

Change subscription settings flow

---

src/main/scala/com/gu/facebook_news_bot/football_transfers/FootballTransfersPoller.scala

The field in the spreadsheet is called `released`.
Also, Editorial _have_ asked for "has" to be changed to "have".

Fix handling of 'released' players

---

src/main/scala/com/gu/facebook_news_bot/services/Facebook.scala

Messages to be sent to facebook are sent to an actor, which maintains a queue of pending http requests.
When a message is given to this actor, the result is expected some time in the future. Recently, the ask request to the actor has occasionally timed out while processing many morning-briefings and transfer rumours simultaneously. The current actor timout of 5 seconds clearly isn't enough at these times.

Increase FB actor timeout

---

src/main/scala/com/gu/facebook_news_bot/BotService.scala
src/main/scala/com/gu/facebook_news_bot/briefing/MorningBriefingPoller.scala
src/main/scala/com/gu/facebook_news_bot/football_transfers/FootballTransferRumoursPoller.scala
src/main/scala/com/gu/facebook_news_bot/state/FootballTransferStates.scala
src/main/scala/com/gu/facebook_news_bot/utils/Notifier.scala

We record when users become uncontactable in order to get a true subscriber count.
If a user does not unusubscribe from notifications formally through our bot, they can prevent us from sending messages in one of the followings ways:
1. Delete the conversation - this is the most common. This means we cannot get the user's data from the FB graph api, and we cannot send them messages. We already record this case in dynamodb.
2. Click "Turn off all messages" in the Manage Messages menu. This means we can still get the user's data from FB graph api, but cannot send them messages. We do not currently record this case.
This change does the following:
1. Records when users become uncontactable through the 2nd option above.
2. Moves the notifications logic in `MorningBriefingPoller` to the new …

Improve recording of uncontactable users

---

cloudformation/cloudformation.yml

To
1. reduce delay in sending out morning briefings
2. ensure the bot responds quickly to messages from users

Increase autoscaling size to 2

---

src/main/scala/com/gu/facebook_news_bot/state/MainState.scala
src/main/scala/com/gu/facebook_news_bot/state/State.scala
src/main/scala/com/gu/facebook_news_bot/state/StateHandler.scala

In general, the receipt of a `postback` means the user has clicked a button.
It's best to avoid using buttons for behaviour that is specific to a state, as buttons persist after the conversation has moved on, meaning the user can later click a button out of context.
However, for the oscar nominations feature we have a legitimate reason to use buttons - for choosing predictions from a carousel.
So this change makes it possible for a state to override handling of postbacks. By default postbacks will still be handled by the `MAIN` state.

Support custom handling of postbacks

---

src/main/scala/com/gu/facebook_news_bot/BotConfig.scala
src/main/scala/com/gu/facebook_news_bot/BotService.scala
src/main/scala/com/gu/facebook_news_bot/football_transfers/FootballTransfersFeedbackPoller.scala
src/main/scala/com/gu/facebook_news_bot/state/FeedbackState.scala
src/main/scala/com/gu/facebook_news_bot/state/FootballTransferStates.scala
src/main/scala/com/gu/facebook_news_bot/state/StateHandler.scala
src/main/scala/com/gu/facebook_news_bot/utils/SQSPoller.scala

We will send out a one-off message to all football transfers subscribers, to ask for feedback.
- Made `FeedbackState` a trait so that it can be used for feedback on specific things.
- Added a new poller to process these notifications. This uses the existing SQS for the football rumours, as we need to send these out today.
TODO - build a more general way of sending out mass messages to a subset of users like this.

Football transfers feedback

---

src/main/scala/com/gu/facebook_news_bot/briefing/CustomBriefing.scala
src/main/scala/com/gu/facebook_news_bot/briefing/MorningBriefingPoller.scala
src/main/scala/com/gu/facebook_news_bot/models/User.scala
src/main/scala/com/gu/facebook_news_bot/utils/FacebookMessageBuilder.scala

Support the publication of custom morning briefings. The user can choose 1-2 topics to include in the carousel. The 5 stories in the carousel are picked as follows:
1. editors-picks[0]
2. topic1[0]
3. editors-picks[1]
4. topic2[0] || topic1[1]
5. editors-picks[2]
The urls will end with `&variant=custom-briefing-<edition>`

Custom briefing pub

---

src/main/scala/com/gu/facebook_news_bot/models/User.scala
src/main/scala/com/gu/facebook_news_bot/services/Capi.scala
src/main/scala/com/gu/facebook_news_bot/state/BriefingTimeQuestionState.scala
src/main/scala/com/gu/facebook_news_bot/state/CustomBriefingQuestionState.scala
src/main/scala/com/gu/facebook_news_bot/state/FootballTransferStates.scala
src/main/scala/com/gu/facebook_news_bot/state/ManageMorningBriefingState.scala
src/main/scala/com/gu/facebook_news_bot/state/RemoveCustomBriefingTopicState.scala
src/main/scala/com/gu/facebook_news_bot/state/State.scala
src/main/scala/com/gu/facebook_news_bot/state/StateHandler.scala
src/main/scala/com/gu/facebook_news_bot/state/YesOrNoState.scala
src/test/resources/facebookRequests/customBriefingTopic.json
src/test/resources/facebookRequests/noCustomBriefingTopic.json
src/test/resources/facebookResponses/customBriefingTopic.json
src/test/resources/facebookResponses/manageMorningBriefing.json
src/test/resources/facebookResponses/noCustomBriefingTopic.json
src/test/scala/com/gu/facebook_news_bot/SubscriptionTest.scala

- During sign-up, users are asked if they'd like to customise their briefing with up to 2 topics.
- From the manage subscription menu, users can add/remove topics.
TODO - send out a one-off message to all existing subscribers to see if they'd like to customise their briefings.

Custom briefing subscription

---

src/main/scala/com/gu/facebook_news_bot/briefing/CustomBriefing.scala

In case a story appears in both editors-picks and a topic's headlines. Keeping with the ordering:
1. editors-picks
2. topic1
3. editors-picks
4. topic2 || topic1
5. editors-picks

Deduplicate stories in custom briefing

---

src/main/scala/com/gu/facebook_news_bot/state/FeedbackState.scala
src/main/scala/com/gu/facebook_news_bot/state/MainState.scala

We get quite a lot of editorial-related comments via the feedback mechanism in the bot.
This change makes it a bit clearer that it's looking for feedback on the bot, and sends a link to Readers' Editor contact details for general messages that are over 200 chars.

Send readers' editor url for long messages

---

build.sbt
cloudformation/cloudformation.yml
facebook-news-bot.service
src/main/scala/com/gu/facebook_news_bot/BotService.scala
src/main/scala/com/gu/facebook_news_bot/services/Capi.scala
src/main/scala/com/gu/facebook_news_bot/state/MainState.scala
src/main/scala/com/gu/facebook_news_bot/state/SearchFeedbackState.scala
src/main/scala/com/gu/facebook_news_bot/state/StateHandler.scala
src/main/scala/com/gu/facebook_news_bot/state/YesOrNoState.scala
src/main/scala/com/gu/facebook_news_bot/utils/FacebookMessageBuilder.scala
src/main/scala/com/gu/facebook_news_bot/utils/Parser.scala
src/test/resources/capiResponses/headlines-search.json
src/test/resources/facebookRequests/trumpHeadlines.json
src/test/resources/facebookResponses/trumpHeadlines.json
src/test/scala/com/gu/facebook_news_bot/DummyCapi.scala
src/test/scala/com/gu/facebook_news_bot/HeadlinesTest.scala
src/test/scala/com/gu/facebook_news_bot/SearchTopicTest.scala

We currently have a hardcoded set of topics, e.g. football, politics. These are mapped to specific sections/tags to ensure good results. If a user enters text containing a topic, the app returns a carousel with the links. If the user's input does not contain any of these hardcoded terms, it simply tells the user it doesn't understand.
- If the user's input does not contain a topic then the app uses NLP to build a syntax tree from it (using http://stanfordnlp.github.io/CoreNLP/)
- Traverses the syntax tree looking for nouns, to build up a list of search terms.
- Uses CAPI's `q=` parameter to search for these terms. E.g. "Tell me about Obama and also Donald Trump" --> `/search?q=Obama+AND+%22Donald+Trump%22`
- The response to the user lists the terms it searched for, e.g. "I think you're …

Use NLP to build capi queries

---

src/main/scala/com/gu/facebook_news_bot/state/CustomBriefingQuestionState.scala

This is a bug(?) I introduced with the NLP change, which models search terms as a special kind of `Topic` called `SearchTopic`.
The ability to add topics to your morning briefing is based on the available `Topic`s, but it should exclude arbitrary search terms!
I discovered this when I noticed that someone had chosen `hunks` as one of their morning briefing topics.

Restrict briefing topics

---

src/main/scala/com/gu/facebook_news_bot/briefing/CustomBriefing.scala

Stories must have a webPublicationDate from the last 24 hours to be included in the custom briefing. Some sections keep the same article at the top for days

Only include stories published in last 24 hours in custom briefing

---

build.sbt
cloudformation/cloudformation.yml
src/main/scala/com/gu/facebook_news_bot/BotConfig.scala
src/main/scala/com/gu/facebook_news_bot/BotService.scala
src/main/scala/com/gu/facebook_news_bot/services/Capi.scala
src/main/scala/com/gu/facebook_news_bot/utils/BadWords.scala
src/test/scala/com/gu/facebook_news_bot/SearchTopicTest.scala

Taken from s3.
Certain words will now not be used when querying for content from capi.
I also removed oscars stuff from cloudformation as it was preventing me from updating it in CODE.

Excluded words list

---

src/main/scala/com/gu/facebook_news_bot/briefing/CustomBriefing.scala
src/main/scala/com/gu/facebook_news_bot/briefing/MorningBriefingPoller.scala
src/main/scala/com/gu/facebook_news_bot/services/Capi.scala
src/test/scala/com/gu/facebook_news_bot/DummyCapi.scala

As an initial cut, we are delivering this to only UK readers. Clicking through on tile will take reader to Morning Briefing articles: https://www.theguardian.com/world/series/guardian-morning-briefing
If there is no fresh article, or the reader is outside UK, standard carousel is sent.
Once content in series is structured, plan is to give users option to consume content in bot.
Example seen on CODE: 
Note: Height of tiles is different due to absence of button, but have decided not to introduce one until we've added the content in bot feature

Add News Digest tile to Morning Briefing
