- index.js
A "quick reply" button to page through the results (headlines or trending).
Also changed the payload string to be json.
> Add 'more' button after links

- index.js
The persistent menu has a "Manage subscription" button. If a non-subscribed user clicks it, ask if they want to subscribe.
Also changed "trending" to "most popular"
> Persistent menu - handle users who are not subscribed 

- index.js
- lib/messages.js
> Randomise messages

- index.js
This is now going into kibana.
E.g.
```
{  
"id":"1249017745129028",
"event":"most_popular",
"messageType":"postback",
"timestamp":"2016-08-23T12:34:13.215Z",
"data":{  
"payload":{  
"event":"most_popular"
}
}
}
{  
"id":"1249017745129028",
"event":"most_popular",
"messageType":"text",
"timestamp":"2016-08-23T12:34:33.210Z",
"data":{  
"text":"More stories",
"payload":{  
"page":5,
"event":"most_popular"
}
}
}
```
> Proper logging

- index.js
- lib/messages.js
It ignored our first American user :(
> Fix processing of negative timezone offsets

- index.js
It failed to get a user's info from FB while doing morning briefings today, and subsequently broke.
> Better handling of errors after facebook requests

- index.js
oops, tested it properly this time!
> Fix morning briefing

- index.js
It lost the campaign code after switching from using buttons to item_urls
@chriswilk
> Include campaign code

- index.js
Standfirst is an optional field
> Handle missing standfirst

- src/main/scala/com/gu/facebook_news_bot/state/MainState.scala
- src/main/scala/com/gu/facebook_news_bot/utils/FacebookMessageBuilder.scala
- src/test/resources/facebookResponses/headlines.json
- src/test/resources/facebookResponses/moreHeadlines.json
- src/test/resources/facebookResponses/morePoliticsHeadlines.json
- src/test/resources/facebookResponses/politicsHeadlines.json
This is consistent with the existing node app.
> Add suggested topic quick_replies after the carousel

- src/main/scala/com/gu/facebook_news_bot/state/EditionQuestionState.scala
> Fix changing edition to australia

- src/main/scala/com/gu/facebook_news_bot/BotService.scala
Log the messages being sent to facebook. I accidentally logged the incoming message, which is already being logged.
> Log outgoing messages

- src/main/scala/com/gu/facebook_news_bot/state/MainState.scala
- src/main/scala/com/gu/facebook_news_bot/state/State.scala
- src/main/scala/com/gu/facebook_news_bot/utils/ResponseText.scala
thanks to @chriswilk for spotting this
> Display menu after greeting

- src/main/scala/com/gu/facebook_news_bot/state/BriefingTimeQuestionState.scala
- src/test/resources/facebookResponses/briefingTime.json
> Display menu after user has been subscribed

- src/main/resources/logback.xml
This is going to fill up the disk now we're getting a lot of traffic
> Turn off debug logging

- src/main/scala/com/gu/facebook_news_bot/services/Capi.scala
> Fix aussie politics

- src/main/scala/com/gu/facebook_news_bot/services/Facebook.scala
This was a TODO that I forgot to do...
The app uses a queue for sending messages to facebook. `queue.offer` returns a result based on the `QueueOfferResult` sealed trait.
I've noticed a couple of error logs caused by the queue rejecting messages. This change will help clarify what the cause is, if it happens again.
> Report all akka queue errors properly

- src/main/scala/com/gu/facebook_news_bot/briefing/MorningBriefingPoller.scala
The lambda that schedules morning briefings publishes the user data from the dynamo table to an SNS topic, to be consumed by the bot app.
This was intended to avoid doing an extra dynamo read in the bot app. But it's a really bad idea because it means the User model in the lambda has to be the same as the User model in the bot app.
This change makes the bot app do the dynamo lookup as well.
> Do not rely on the scheduler's User model

- src/main/scala/com/gu/facebook_news_bot/football_transfers/FootballTransfersPoller.scala
The Sports desk has asked us to handle the case where a player with no previous team joins a new team.
@tsop14
> Support 'free agent' transfers

- src/main/scala/com/gu/facebook_news_bot/briefing/MorningBriefingPoller.scala
- src/main/scala/com/gu/facebook_news_bot/state/FootballTransferStates.scala
- src/test/resources/facebookResponses/footballTransfers/newUser.json
- src/test/resources/facebookResponses/footballTransfers/noMoreTeams.json
And some copy changes.
@chriswilk
> Ask users if they want morning briefing after transfers question

- src/main/scala/com/gu/facebook_news_bot/briefing/MorningBriefingPoller.scala
Just realised it'll use UTC when deciding if it's new year - it should use the user's timezone
> Use correct timezone for new year

- src/main/scala/com/gu/facebook_news_bot/utils/SQSPoller.scala
In late December, 9 people received the transfer rumours link twice in a row.
This happened because it failed to delete the messages from the SQS queue on the 1st attempt, meaning the same 9 messages were read again when the app next polled the queue.
_It is always preferable to send no message than to risk sending it multiple times._
With this change, the app defends against message deletion failures. Each `SQSPoller` actor (we currently have 3, for different kinds of notifications) will try to delete a batch of messages from SQS 3 more times before giving up. If it still can't delete them, the actor kills itself (the supervisor does not restart the actor in this case) to avoid spamming users. This means the scheduled messages on that queue will no longer be sent to users until the app …
> Handle SQS message deletion failures

- src/main/scala/com/gu/facebook_news_bot/briefing/MorningBriefingPoller.scala
Also rewrite the horrible isNewYear function I wrote on new years eve
> Remove logic for football transfers question on new year

- src/main/scala/com/gu/facebook_news_bot/utils/SQSPoller.scala
The actor responsible for queueing up messages to be sent to facebook sometimes fails to respond (akka.pattern.AskTimeoutException) while processing many scheduled messages.
This has been causing the actor responsible for preparing football transfer rumour messages to stop working.
This change ensures that the `SQSPoller` actors continue polling after the facebook actor has failed to respond.
I will investigate the cause of the timeouts separately.
> Handle failed scheduled messages

- src/main/scala/com/gu/facebook_news_bot/football_transfers/FootballTransferRumoursPoller.scala
- src/main/scala/com/gu/facebook_news_bot/football_transfers/FootballTransfersPoller.scala
- src/test/scala/com/gu/facebook_news_bot/FootballTransferTest.scala
After the rumours notification and any transfer notifications.
@chriswilk
> Quick replies after football notifications

- src/main/scala/com/gu/facebook_news_bot/football_transfers/FootballTransferRumoursPoller.scala
accidentally removed this in previous commit
> Log rumours notifications

- src/main/scala/com/gu/facebook_news_bot/football_transfers/FootballTransfersPoller.scala
Requested by the Sports desk.
Unfortunately the message can be too long. Not much we can do about this, but the user can click the link below it.
> New transfer types

- src/main/scala/com/gu/facebook_news_bot/state/StateHandler.scala
> Tidy StateHandler

- src/main/scala/com/gu/facebook_news_bot/models/UserNoms.scala
Which given a user ID carries the choices made by the corresponding user.
> Introducing the type UserNoms

- src/main/scala/com/gu/facebook_news_bot/BotConfig.scala
- src/main/scala/com/gu/facebook_news_bot/BotService.scala
- src/main/scala/com/gu/facebook_news_bot/state/FootballTransferStates.scala
- src/main/scala/com/gu/facebook_news_bot/stores/UserStore.scala
- src/test/scala/com/gu/facebook_news_bot/TestService.scala
- src/test/scala/com/gu/facebook_news_bot/UserStoreTest.scala
Refactorings in UserStore and introducing userNomsTable for future use
> Refactorings in UserStore and introducing userNomsTable for future use

- src/test/scala/com/gu/facebook_news_bot/util/JsonHelpers.scala
For loading in a JSON array of expected messages for the tests.
> Decoder for messages seq

- build.sbt
- src/main/scala/com/gu/facebook_news_bot/models/User.scala
- src/main/scala/com/gu/facebook_news_bot/models/UserNoms.scala
- src/main/scala/com/gu/facebook_news_bot/state/OscarsNomsStates.scala
- src/main/scala/com/gu/facebook_news_bot/state/StateHandler.scala
- src/main/scala/com/gu/facebook_news_bot/stores/UserStore.scala
- src/test/resources/facebookRequests/oscarsNoms/enterBestDirector.json
- src/test/resources/facebookRequests/oscarsNoms/enterBestPicture.json
- src/test/resources/facebookRequests/oscarsNoms/newUser.json
- src/test/resources/facebookResponses/oscarsNoms/enterBestDirector.json
- src/test/resources/facebookResponses/oscarsNoms/enterBestPicture.json
- src/test/resources/facebookResponses/oscarsNoms/newUser.json
- src/test/scala/com/gu/facebook_news_bot/LocalDynamoDB.scala
- src/test/scala/com/gu/facebook_news_bot/OscarsNomsTest.scala
- src/test/scala/com/gu/facebook_news_bot/UserStoreTest.scala
Work done with @annebyrne last week. I squashed all our commits.
> Updates in OscarsNomsStates and some tests

- src/main/scala/com/gu/facebook_news_bot/state/MainState.scala
To stop people from signing up
> Remove football transfers from the menu

- src/main/scala/com/gu/facebook_news_bot/briefing/MorningBriefingPoller.scala
- src/main/scala/com/gu/facebook_news_bot/utils/ResponseText.scala
- src/test/resources/facebookResponses/noCustomBriefingTopic.json
On 8th Feb all morning briefings will be followed by a message asking if they'd like to customise their briefings.
> Advertise custom briefings

- src/main/scala/com/gu/facebook_news_bot/models/UserNoms.scala
- src/main/scala/com/gu/facebook_news_bot/state/OscarsNomsStates.scala
- src/test/resources/facebookResponses/oscarsNoms/enterBestDirector.json
- src/test/resources/facebookResponses/oscarsNoms/enterBestPicture.json
Examples of in-game play below:
> Add images to Oscar Nominations Game

- src/main/scala/com/gu/facebook_news_bot/briefing/CustomBriefing.scala
- src/main/scala/com/gu/facebook_news_bot/briefing/MorningBriefingPoller.scala
I left out the "Good morning" message that comes with the carousel, looks a bit weird without it
> Initial message with custom briefing

- cloudformation/cloudformation.yml
forgot to include this in the last PR
> Use t2.small

- src/main/scala/com/gu/facebook_news_bot/briefing/MorningBriefingPoller.scala
On 15th February, an invite to the Oscars game will be triggered to existing users with their morning briefing. An example of interaction is below:
> Advertise Oscars Predictions Game to existing user base

- src/main/scala/com/gu/facebook_news_bot/state/OscarsNomsStates.scala
> Add additional quick reply for existing users

- build.sbt
- src/main/scala/com/gu/facebook_news_bot/BotConfig.scala
- src/main/scala/com/gu/facebook_news_bot/services/Facebook.scala
- src/main/scala/com/gu/facebook_news_bot/stores/UserStore.scala
- src/main/scala/com/gu/facebook_news_bot/utils/JsonHelpers.scala
- src/main/scala/com/gu/facebook_news_bot/utils/Notifier.scala
- src/test/scala/com/gu/facebook_news_bot/UserStoreTest.scala
- src/test/scala/com/gu/facebook_news_bot/util/JsonHelpers.scala
This allows us to use the lastest content-api-models and scanamo
> Circe 0.7.0

- src/main/scala/com/gu/facebook_news_bot/BotConfig.scala
- src/main/scala/com/gu/facebook_news_bot/briefing/MorningBriefingPoller.scala
we're disabling this for now...
> New switch for morning digest
